import {today,addDays,weekStart,occurrences,progress,projectProgress,updateOccurrence,removeTask,uid,validate,TASK_STATUSES,IDEA_STATUSES,PROJECT_STATUSES,PRIORITIES} from './model.js';
import {LocalRepository,STORAGE_KEY} from './storage.js';
const $ = s=>document.querySelector(s);
const esc = v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={Dashboard:'<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/>',Schedule:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 11h18"/>',Ideas:'<path d="M9 18h6m-5 3h4M8 14a7 7 0 1 1 8 0c-1 1-1 2-1 2H9s0-1-1-2Z"/>',Projects:'<path d="M3 7V5a2 2 0 0 1 2-2h5l3 4h6a2 2 0 0 1 2 2v10H3Z"/>',Settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="16" cy="17" r="3"/>'};
const icon=k=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true">${icons[k]||''}</svg>`;
let repo, state, view=location.hash.slice(1)||'Dashboard', offset=0, area='', status='', search='', rows=new Map(), editorRevision=0, revision=0;
const date=()=>today(state.workspace.timeZone);
const pretty=(d,short=false)=>d?new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',...(short?{}:{weekday:'short'}),timeZone:'UTC'}).format(new Date(d+'T12:00:00Z')):'Unscheduled';
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function mutate(fn,message='Saved'){try{const next=structuredClone(state);fn(next);repo.save(next);state=next;revision++;render();toast(message);return true;}catch(e){toast('Could not save. '+e.message);return false;}}
function options(values,selected,empty){return (empty!==undefined?`<option value="">${esc(empty)}</option>`:'')+values.map(v=>`<option value="${esc(typeof v==='string'?v:v.id)}" ${(typeof v==='string'?v:v.id)===selected?'selected':''}>${esc(typeof v==='string'?v:v.title)}</option>`).join('');}
const badge=(value)=>`<span class="badge ${value==='High'?'high':value==='Completed'||value==='Live'||value==='Used'?'good':''}">${esc(value)}</span>`;
const bar=(n)=>`<div class="bar" role="progressbar" aria-label="Progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${n}"><i style="width:${n}%"></i></div>`;
const blank=(text)=>`<div class="empty"><span>◇</span><p>${text}</p></div>`;
function taskRow(t){rows.set(t.key,t);return `<div class="task ${t.status==='Completed'?'completed':''}"><button class="check" data-complete="${esc(t.key)}" aria-label="${t.status==='Completed'?'Reopen':'Complete'} ${esc(t.title)}" aria-pressed="${t.status==='Completed'}">${t.status==='Completed'?'✓':''}</button><button class="task-detail" data-edit-task="${esc(t.key)}"><strong>${esc(t.title)}</strong><span>${esc(t.area)} <b>·</b> ${t.time?esc(t.time)+' '+esc(state.workspace.timeZone.split('/').pop().replaceAll('_',' ')):'Any time'} ${t.recurring?'<b>·</b> Weekly':''} ${t.status==='In Progress'?'<b>·</b> In progress':''}</span></button>${t.priority==='High'?'<span class="priority-dot" title="High priority"></span>':''}<span class="task-arrow" aria-hidden="true">↗</span></div>`;}
function panel(title,body,action='',cls=''){return `<section class="panel ${cls}"><div class="panel-heading"><h2>${title}</h2>${action}</div>${body}</section>`;}
const goto=(v,label='View all')=>`<button class="text-button" data-nav="${v}">${label} <span aria-hidden="true">↗</span></button>`;
function dashboard(){
 const d=date(),start=weekStart(d),weekly=occurrences(state,start,addDays(start,6)),p=progress(weekly),due=occurrences(state,d,d),overdue=occurrences(state,'',addDays(d,-1)).filter(t=>t.status!=='Completed');
 const upcoming=occurrences(state,addDays(d,1),addDays(d,14)).filter(t=>t.status!=='Completed').slice(0,4);
 const active=state.projects.filter(p=>!['Completed','Live'].includes(p.status));
 const ideas=state.ideas.filter(i=>i.status!=='Used');
 return `<div class="intro"><div><p class="eyebrow">YOUR WORK, IN FOCUS</p><h1>Make room for progress<span>.</span></h1><p>A clear day. A little momentum. One thing at a time.</p></div><button class="primary" data-add="tasks">＋ Add task</button></div>
 <div class="stats"><div><span>Today’s work</span><strong>${due.filter(t=>t.status!=='Completed').length}<small>tasks remaining</small></strong></div><div><span>This week</span><strong>${p.done}<small>of ${p.total} completed</small></strong></div><div><span>Ideas to explore</span><strong>${ideas.length}<small>ready for a next step</small></strong></div><div><span>Projects in motion</span><strong>${active.length}<small>room to grow</small></strong></div></div>
 <div class="dashboard-grid"><div class="main-column">${panel(`<span class="live-dot"></span> Today <span class="count">${due.length}</span>`, `<div class="section-note">${pretty(d)} <span>${esc(state.workspace.timeZone.replaceAll('_',' '))}</span></div>${due.length?due.map(taskRow).join(''):blank('Nothing scheduled today. Enjoy the space, or add a task.')}`,goto('Schedule','Your schedule'))}
 ${overdue.length?panel(`Needs attention <span class="count">${overdue.length}</span>`,overdue.slice(0,4).map(t=>`<div class="overdue-date">${pretty(t.date)}</div>${taskRow(t)}`).join(''),goto('Schedule','See overdue')):''}
 ${panel('Upcoming',upcoming.length?upcoming.map(t=>`<div class="upcoming-row"><div class="date-chip"><strong>${t.date.slice(8)}</strong><span>${pretty(t.date,true).split(' ')[1]}</span></div><div class="upcoming-task">${taskRow(t)}</div></div>`).join(''):blank('Your next two weeks are clear.'),goto('Schedule'))}</div>
 <div class="side-column">${panel('This week',`<div class="week-progress"><div class="ring" style="--progress:${p.percent}%"><strong>${p.percent}<span>%</span></strong></div><div><h3>${p.done? 'Keep it flowing.':'A fresh start.'}</h3><p>${p.total-p.done} tasks left this week</p><span class="subtle">${pretty(start,true)} to ${pretty(addDays(start,6),true)}</span></div></div>${bar(p.percent)}`,'','weekly-panel')}
 ${panel('Ideas in the making',`<div class="pipeline">${['Idea','Draft','Scheduled'].map(s=>`<div><strong>${state.ideas.filter(i=>i.status===s).length}</strong><span>${s==='Idea'?'Ideas':s==='Draft'?'Drafts':'Scheduled'}</span></div>`).join('')}</div>${ideas.slice(0,2).map(i=>`<button class="mini-card" data-edit-idea="${esc(i.id)}"><span class="idea-symbol">✧</span><span>${esc(i.title)}<small>${esc(i.area)}</small></span></button>`).join('')}`,goto('Ideas'))}
 ${panel('Project progress',state.projects.slice().sort((a,b)=>(a.status==='In Progress'?-1:1)-(b.status==='In Progress'?-1:1)).slice(0,3).map(p=>{const n=projectProgress(state,p,d);return `<button class="project-mini" data-edit-project="${p.id}"><span>${esc(p.title)}<small>${n.percent}%</small></span>${bar(n.percent)}<em>${esc(p.status)}</em></button>`}).join('')||blank('Create your first project.'),goto('Projects'))}</div></div>`;
}
function toolbar(kind){return `<div class="toolbar"><label class="search"><span aria-hidden="true">⌕</span><input id="search" type="search" aria-label="Search ${kind}" placeholder="Search ${kind}…" value="${esc(search)}"></label><select id="area-filter" aria-label="Filter by area">${options(state.areas,area,'All areas')}</select><select id="status-filter" aria-label="Filter by status">${options(kind==='tasks'?TASK_STATUSES:kind==='ideas'?IDEA_STATUSES:PROJECT_STATUSES,status,'All statuses')}</select></div>`;}
const filtered=list=>list.filter(t=>(!area||t.area===area)&&(!status||t.status===status)&&(!search||[t.title,t.notes,t.area].join(' ').toLowerCase().includes(search.toLowerCase())));
function heading(title,sub,kind){return `<div class="intro"><div><p class="eyebrow">PLAN. CREATE. GROW.</p><h1>${title}<span>.</span></h1><p>${sub}</p></div><button class="primary" data-add="${kind}">＋ Add ${kind==='ideas'?'idea':kind==='projects'?'project':'task'}</button></div>`;}
function schedule(){const start=addDays(weekStart(date()),offset*7),end=addDays(start,6),list=filtered(occurrences(state,start,end));const late=filtered(occurrences(state,'',addDays(date(),-1))).filter(t=>t.status!=='Completed');const unscheduled=filtered(state.tasks.filter(t=>!t.date).map(t=>({...t,key:t.id,originalDate:''})));return heading('Your schedule','A little structure. Plenty of breathing room.','tasks')+toolbar('tasks')+`<div class="week-nav"><div><button class="icon-button" data-week="-1" aria-label="Previous week">‹</button><h2>${pretty(start,true)} to ${pretty(end,true)}</h2><button class="icon-button" data-week="1" aria-label="Next week">›</button></div><button class="secondary" data-this-week>This week</button></div><p class="subtle">Times follow ${esc(state.workspace.timeZone.replaceAll('_',' '))}. Weekly tasks repeat on the same weekday.</p><div class="schedule-days">${Array.from({length:7},(_,i)=>{const d=addDays(start,i),dayTasks=list.filter(t=>t.date===d);return panel(`${pretty(d)}${d===date()?'<span class="today-label">Today</span>':''}`,dayTasks.length?dayTasks.map(taskRow).join(''):'<p class="free-day">A little breathing room.</p>',`<button class="text-button" data-add-date="${d}" aria-label="Add task on ${pretty(d)}">＋</button>`,d===date()?'is-today':'')}).join('')}</div>${unscheduled.length?panel('Unscheduled',unscheduled.map(taskRow).join('')):''}${late.length?panel(`Overdue · ${late.length}`,late.map(t=>`<div class="overdue-date">${pretty(t.date)}</div>${taskRow(t)}`).join('')):''}`;}
function ideas(){const list=filtered(state.ideas);return heading('A place for possibilities','Capture it now. Make something of it when you’re ready.','ideas')+toolbar('ideas')+`<div class="card-grid">${list.map(i=>`<button class="record-card" data-edit-idea="${i.id}"><div class="card-top"><span class="idea-symbol">✧</span>${badge(i.status)}</div><span class="record-area">${esc(i.area)}</span><h2>${esc(i.title)}</h2><p>${esc(i.notes)}</p><div class="card-bottom">${badge(i.priority)}<span>Edit idea ↗</span></div></button>`).join('')||blank('No ideas here yet. Capture your next one.')}</div>`;}
function projects(){return heading('Build what comes next','Keep the next step in sight.','projects')+toolbar('projects')+`<div class="card-grid">${filtered(state.projects).map(p=>{const n=projectProgress(state,p,date());return `<button class="record-card" data-edit-project="${p.id}"><div class="card-top">${icon('Projects')}${badge(p.status)}</div><span class="record-area">${esc(p.area)}</span><h2>${esc(p.title)}</h2><p>${esc(p.notes)}</p><div class="progress-caption"><span>${n.linked?'Linked task progress':'Project progress'}</span><strong>${n.percent}%</strong></div>${bar(n.percent)}<div class="card-bottom">${badge(p.priority)}<span>Open project ↗</span></div></button>`}).join('')||blank('No projects here yet. Start with one clear goal.')}</div>`;}
function settings(){return `<div class="intro"><div><p class="eyebrow">MAKE IT YOURS</p><h1>A simpler workspace<span>.</span></h1><p>Just the essentials, set up your way.</p></div></div><div class="settings-grid">${panel('Your workspace',`<form id="workspace-form"><label>Workspace name<input name="name" required maxlength="100" value="${esc(state.workspace.name)}"></label><label>Schedule timezone<select name="timeZone">${options([...new Set([state.workspace.timeZone,'Europe/London','America/New_York','Asia/Manila','Australia/Sydney','UTC'])],state.workspace.timeZone)}</select></label><p class="subtle">Changing timezone keeps task dates and clock times as entered. The original UK and ET times stay in each seeded task’s reference notes.</p><button class="primary">Save preferences</button></form>`)}${panel('Areas of work',`<p class="subtle">Use any area that fits your work.</p><form id="area-form" class="inline-form"><input name="area" required maxlength="100" aria-label="New area name" placeholder="Add a new area"><button class="secondary">Add</button></form><div class="area-chips">${state.areas.map(a=>`<span>${esc(a)}<button data-remove-area="${esc(a)}" aria-label="Remove ${esc(a)} area">×</button></span>`).join('')}</div><p class="subtle">An area can be removed when no task, idea or project uses it.</p>`)}${panel('Your data, in your hands',`<p>Saved in this browser on this device. Export a backup to keep a copy or move your work to another browser.</p><div class="button-row"><button class="secondary" data-export>Export backup</button><button class="secondary" data-import>Restore backup</button></div><input hidden type="file" id="import-file" accept="application/json,.json"><p class="subtle">Restoring replaces this browser’s Flow data. Clearing browser data removes your work. There is no cloud sync in V1.</p>`)}${panel('EXCEDERE | FLOW',`<div class="about-brand"><img src="./assets/flow-mark.svg" alt="Flow square identity" width="60" height="60"><div><h3>Plan. Create. Grow.</h3><p>Business Beyond Borders</p></div></div><p class="subtle">Version 1.0 · A little more focus, every day.</p>`)}</div>`;}
function render(){if(!icons[view])view='Dashboard';rows.clear();$('#app').innerHTML=`<aside class="sidebar"><a class="brand" href="#Dashboard"><img src="./assets/flow-mark.svg" width="44" height="44" alt=""><div>EXCEDERE <b>| FLOW</b><small>Plan. Create. Grow.</small></div></a><div class="workspace"><span class="workspace-avatar">${esc(state.workspace.name.slice(0,1).toUpperCase())}</span><div>${esc(state.workspace.name)}<small>Your workspace</small></div></div><p class="nav-caption">WORKSPACE</p><nav aria-label="Main navigation">${Object.keys(icons).map(v=>`<a href="#${v}" class="${view===v?'active':''}" ${view===v?'aria-current="page"':''}>${icon(v)}<span>${v}</span>${view===v?'<i></i>':''}</a>`).join('')}</nav><div class="sidebar-footer"><span class="live-dot"></span> Saved on this device<small>BUSINESS BEYOND BORDERS</small></div></aside><div class="shell"><header class="topbar"><span>${view}</span><div><span class="top-date">${pretty(date())}</span><span class="avatar">${esc(state.workspace.name.slice(0,1).toUpperCase())}</span></div></header><main id="main" tabindex="-1">${({Dashboard:dashboard,Schedule:schedule,Ideas:ideas,Projects:projects,Settings:settings})[view]()}</main><footer class="main-footer"><span>EXCEDERE <b>| FLOW</b></span><span>One thing at a time.</span></footer></div>`;bind();}
function navigate(v){if(view===v){render();return;}location.hash=v;}
window.addEventListener('hashchange',()=>{view=location.hash.slice(1);area='';status='';search='';render();});
function field(label,name,value='',type='text',extra=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function select(label,name,values,value,empty){return `<label>${label}<select name="${name}">${options(values,value,empty)}</select></label>`;}
function showDialog(html){editorRevision=revision;$('#editor').innerHTML=html;$('#editor').showModal();$('#editor').querySelector('[data-close]')?.addEventListener('click',()=>$('#editor').close());}
function openEditor(kind,record=null,newDate=date()) {
 const task=kind==='tasks',idea=kind==='ideas',r=record||{title:'',area:state.areas[0]||'Admin',priority:'Medium',status:task?'Not Started':idea?'Idea':'Not Started',notes:'',date:newDate,time:'',projectId:'',progress:0};
 const name=task?'task':idea?'idea':'project';
 showDialog(`<form id="record-form"><div class="dialog-heading"><div><p class="eyebrow">${record?'MAKE IT WORK FOR YOU':'A LITTLE MOMENTUM'}</p><h2 id="dialog-title">${record?'Edit':'New'} ${name}</h2></div><button type="button" class="icon-button" data-close aria-label="Close editor">×</button></div>${field('Title','title',r.title,'text','required maxlength="300" autofocus')}<div class="form-grid"><label>Area<input name="area" list="area-options" value="${esc(r.area)}" required maxlength="100"><datalist id="area-options">${options(state.areas)}</datalist></label>${select('Priority','priority',PRIORITIES,r.priority)}${select('Status','status',task?TASK_STATUSES:idea?IDEA_STATUSES:PROJECT_STATUSES,r.status)}${task?select('Project','projectId',state.projects,r.projectId,'No project'):''}${task?field('Date','date',r.date,'date',r.recurring?'required':'')+field('Time (workspace timezone)','time',r.time,'time'):''}${!task&&!idea?field('Progress (%)','progress',r.progress,'number','required min="0" max="100" step="1"'):''}</div>${task&&!record?'<label class="checkbox-label"><input type="checkbox" name="recurring"> Repeat every week on this day</label>':''}${task&&record?.recurring?'<p class="form-note">You’re editing this occurrence only. Other weeks keep their own schedule and status.</p>':''}${!task&&!idea?'<p class="form-note">Linked tasks calculate progress automatically. Otherwise use the percentage above.</p>':''}<label>${!task&&!idea?'Next action / notes':'Notes'}<textarea name="notes" rows="4" maxlength="10000">${esc(r.notes)}</textarea></label>${r.source?`<p class="form-note">Original weekly plan: ${esc(r.source.day)} · UK ${esc(r.source.timeUK)} · ET ${esc(r.source.timeET)}. These are the original reference times, not a live timezone conversion.</p>`:''}<p class="form-error" role="alert"></p><div class="dialog-actions">${record?'<button type="button" class="danger" data-delete>Delete</button>':'<span></span>'}<div><button type="button" class="secondary" data-cancel>Cancel</button><button class="primary">Save ${name}</button></div></div></form>`);
 $('#editor [data-cancel]').onclick=()=>$('#editor').close();
 $('#record-form').onsubmit=e=>{e.preventDefault();if(editorRevision!==revision){$('#editor .form-error').textContent='Your data changed in another tab. Close this editor and reopen the record before saving.';return;}
 const f=new FormData(e.target);const patch={title:f.get('title').trim(),area:f.get('area').trim(),priority:f.get('priority'),status:f.get('status'),notes:f.get('notes')};
 if(!patch.title||!patch.area){$('#editor .form-error').textContent='Please enter a title and area.';return;}
 if(task) Object.assign(patch,{date:f.get('date'),time:f.get('time'),projectId:f.get('projectId')});
 if(task&&!record&&f.get('recurring')&&!patch.date){$('#editor .form-error').textContent='Choose a date for your weekly task.';return;}
 if(!task&&!idea)patch.progress=Number(f.get('progress'));
 if(mutate(s=>{if(!s.areas.includes(patch.area))s.areas.push(patch.area);if(record){if(task)updateOccurrence(s,record,patch);else Object.assign(s[kind].find(x=>x.id===record.id),patch);}else s[kind].push({...patch,id:uid(),workspaceId:s.workspace.id,...(task?{recurring:!!f.get('recurring')}:{})});},`${name[0].toUpperCase()+name.slice(1)} saved`))$('#editor').close();};
 if(record)$('#editor [data-delete]').onclick=()=>confirmDelete(kind,record);
}
function confirmDelete(kind,r){$('#editor').close();showDialog(`<div class="dialog-heading"><h2 id="dialog-title">Delete ${kind==='tasks'?'task':kind==='ideas'?'idea':'project'}?</h2><button class="icon-button" data-close aria-label="Close">×</button></div><p>${esc(r.title)}</p><p class="subtle">This cannot be undone.${kind==='projects'?' Linked tasks will be kept without a project.':''}</p>${r.recurring?'<label class="checkbox-label"><input id="delete-series" type="checkbox"> Delete the entire weekly series, including history</label>':''}<div class="dialog-actions"><button class="secondary" data-cancel>Cancel</button><button class="danger solid" data-confirm-delete>Delete</button></div>`);$('#editor [data-cancel]').onclick=()=>$('#editor').close();$('#editor [data-confirm-delete]').onclick=()=>{if(editorRevision!==revision){toast('Data changed. Close and reopen this record.');return;}const series=$('#delete-series')?.checked;if(mutate(s=>{if(kind==='tasks')removeTask(s,r,series);else{s[kind]=s[kind].filter(x=>x.id!==r.id);if(kind==='projects'){s.tasks.forEach(t=>{if(t.projectId===r.id)t.projectId=''});Object.values(s.overrides).forEach(t=>{if(t.projectId===r.id)t.projectId=''})}}},'Deleted'))$('#editor').close();};}
function download(contents,name){const url=URL.createObjectURL(new Blob([contents],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function restore(file){if(!file)return;if(file.size>10000000){toast('Choose a backup smaller than 10 MB.');return;}file.text().then(raw=>{let imported;try{imported=validate(JSON.parse(raw));}catch(e){toast(e.message);return;}showDialog(`<h2 id="dialog-title">Restore this backup?</h2><p>This replaces the current workspace with ${esc(imported.workspace.name)}: ${imported.tasks.length} tasks, ${imported.ideas.length} ideas and ${imported.projects.length} projects.</p><p>Export your current work first if you need to keep it.</p><div class="button-row"><button class="secondary" data-current-export>Export current data</button><button class="secondary" data-close>Cancel</button><button class="primary" data-restore>Restore</button></div>`);$('#editor [data-current-export]').onclick=()=>download(repo.raw(),'flow-before-restore.json');$('#editor [data-restore]').onclick=()=>{try{repo.save(imported);state=imported;revision++;$('#editor').close();render();toast('Backup restored');}catch(e){toast('Could not restore. '+e.message);}};}).catch(()=>toast('This backup could not be read.'));}
function bind(){
 document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));
 document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openEditor(b.dataset.add));
 document.querySelectorAll('[data-add-date]').forEach(b=>b.onclick=()=>openEditor('tasks',null,b.dataset.addDate));
 document.querySelectorAll('[data-edit-task]').forEach(b=>b.onclick=()=>openEditor('tasks',rows.get(b.dataset.editTask)));
 document.querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>{const r=rows.get(b.dataset.complete);mutate(s=>updateOccurrence(s,r,{status:r.status==='Completed'?'Not Started':'Completed'}),r.status==='Completed'?'Task reopened':'One more thing done.');});
 document.querySelectorAll('[data-edit-idea]').forEach(b=>b.onclick=()=>openEditor('ideas',state.ideas.find(i=>i.id===b.dataset.editIdea)));
 document.querySelectorAll('[data-edit-project]').forEach(b=>b.onclick=()=>openEditor('projects',state.projects.find(i=>i.id===b.dataset.editProject)));
 document.querySelectorAll('[data-week]').forEach(b=>b.onclick=()=>{offset+=Number(b.dataset.week);render()});
 if($('[data-this-week]'))$('[data-this-week]').onclick=()=>{offset=0;render()};
 if($('#area-filter'))$('#area-filter').onchange=e=>{area=e.target.value;render()};
 if($('#status-filter'))$('#status-filter').onchange=e=>{status=e.target.value;render()};
 if($('#search'))$('#search').oninput=e=>{const pos=e.target.selectionStart;search=e.target.value;render();$('#search').focus();try{$('#search').setSelectionRange(pos,pos)}catch{}};
 if($('#workspace-form'))$('#workspace-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(!f.get('name').trim())return;mutate(s=>{s.workspace.name=f.get('name').trim();s.workspace.timeZone=f.get('timeZone')});};
 if($('#area-form'))$('#area-form').onsubmit=e=>{e.preventDefault();const a=new FormData(e.target).get('area').trim();if(a)mutate(s=>{if(!s.areas.some(x=>x.toLowerCase()===a.toLowerCase()))s.areas.push(a);});};
 document.querySelectorAll('[data-remove-area]').forEach(b=>b.onclick=()=>{const a=b.dataset.removeArea;if([...state.tasks,...state.ideas,...state.projects,...Object.values(state.overrides)].some(r=>r.area===a)){toast('This area is in use. Move its records to another area first.');return;}mutate(s=>s.areas=s.areas.filter(x=>x!==a),'Area removed');});
 if($('[data-export]'))$('[data-export]').onclick=()=>download(JSON.stringify(state,null,2),`excedere-flow-${date()}.json`);
 if($('[data-import]'))$('[data-import]').onclick=()=>$('#import-file').click();
 if($('#import-file'))$('#import-file').onchange=e=>restore(e.target.files[0]);
}
window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY){try{if(e.newValue===null)throw Error('Saved data was removed in another tab. Reload before editing.');state=validate(JSON.parse(e.newValue));revision++;render();toast('Updated from another tab');}catch(err){revision++;toast(err.message);}}});
function boot(){try{repo=new LocalRepository();state=repo.load();render();}catch(e){$('#app').innerHTML=`<main class="recovery"><img src="./assets/flow-mark.svg" width="72" alt="Flow"><h1>Your work comes first.</h1><p>${esc(e.message)}</p><p>Browser storage may be unavailable, full, or contain an unsupported backup. No existing data has been overwritten.</p><div class="button-row"><button class="secondary" id="recover-export">Export saved data</button><label class="secondary">Restore backup<input type="file" id="recovery-file" accept=".json" hidden></label><button class="primary" id="retry">Try again</button></div></main>`;$('#recover-export').onclick=()=>{try{download(repo.raw(),'flow-recovery.json')}catch{toast('Browser storage is not accessible.')}};$('#recovery-file').onchange=e=>restore(e.target.files[0]);$('#retry').onclick=boot;}}
boot();
setInterval(()=>{if(state&&!$('#editor').open){const current=date();if(current!==window.lastFlowDay){window.lastFlowDay=current;render();}}},60000);
